import Header from "@/app/layout/header";
import { Inter } from "next/font/google";
import "./globals.css";
import "./table.css";
import "./popup.css";
import Footer from "./layout/footer";
// import SideNavigation from "./layout/side-navigation";
import SubHeader from "./layout/sub-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Payworks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <SubHeader />
        {children}
        <Footer />
        </body>
    </html>
  );
}
